# CV2 Debug Flags
ENABLE_VISUAL_GEOMETRIC_DETECTORS = False
ENABLE_VISUAL_TEXT_RECOGNITION = False

# Terminal Output Vars
ENABLE_DEBUG_ROI_INFO = True
ENABLE_EXTERNAL_DEBUG_CONSOLE = False
ENABLE_DEBUG_CONSOLE = False
